# requirements.yml
collections:
  - name: env.setup
    source: https://github.com/yourusername/env.setup.git
    type: git
    version: main
    # Or use tar instead:
    #source: ./env-setup-1.0.0.tar.gz


